### PR TITLE
Pipenv

### PR DESCRIPTION
**Pull request by puzza007**

### CODE REVIEW

**Comment by kylemcdonald** [comment]
thanks for this contribution!

but from what i understand of [pipenv](https://github.com/kennethreitz/pipenv) it will automatically create this file if one doesn't already exist. is there something that this file fixes that pipenv isn't already doing automatically?

thanks again!

**Comment by puzza007** [comment]
My pleasure :)

I added it because I don't usually want to install deps systemwide.

The `Pipfile` specifies the deps and `Pipfile.lock` keeps them at known versions (until you want to upgrade). I created the `Pipfile` using `pipenv` and was then able to get rid of `requirements.txt`.

**Comment by kylemcdonald** [comment]
Thanks for explaining! I can see how pipenv file would be more precise than the requirements file.

That said, because I'm not a regular pipenv user myself and haven't run into it before (I find more people using requirements.txt) I'm going to push this to a branch https://github.com/kylemcdonald/FreeWifi/tree/pipenv instead of pulling it to master.

If you would like to modify this to bring the `requirements.txt` file and revert the readme to cater to people who don't use pipenv by default, I'm happy to push it to master.

**Comment by puzza007** [comment]
Sounds good 😄 

I've updated this branch accordingly

**Comment by kylemcdonald** [comment]
thanks! sorry for all the explaining. and thanks for fixing the tqdm dependency, i totally forgot :)

**Pull request merged**
